name: The Andy Baker Show
favicon: null
layout_spectrum: 0.39589
typography_spectrum: 0.01199
title: The Andy Baker Show
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0507'
    - '#fdf6e4'
    - '#cec4a9'
    - '#496100'
    - '#9c9118'
  brandStrength: 0.5625
  lightness: 0.5507649
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
