name: The Andy Baker Show
favicon: null
layout_spectrum: 0.39589
typography_spectrum: 0.35999
title: The Andy Baker Show
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121d1f'
    - '#c1b5a7'
    - '#868688'
    - '#b9d4ff'
    - '#6b5f49'
  brandStrength: 0.5625
  lightness: 0.5507649
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
