name: The Andy Baker Show
favicon: null
layout_spectrum: 0.84715
typography_spectrum: 0.35999
title: The Andy Baker Show
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e1422'
    - '#99acbc'
    - '#fffeff'
    - '#e9dcb0'
    - '#675b3f'
  brandStrength: 0.5625
  lightness: 0.5507649
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
